### PR TITLE
Feat/md5 auto header for s3

### PR DESCRIPTION
**Pull request by sven-schubert**

### CODE REVIEW

**Comment by pplu** [comment]
Hello!

  I see and love the intention behind this PR. There are a couple of places in the SDK where a similar approach would be needed too.

  Would you consider an alternative to the 'AutoInHeader' role in the following way: when you want a value to be filled in by the SDK when it's not specified, make it a "lazy => 1, default => sub { ... }". That way, also, if the user specifies a value, it will prevail, but if not specified the default kicks in. This way it would be valid for any place a parameter can be (Headers, Body, etc), while I think that it simplifies code a bit.

  Please note I think that the PR is still OK, but I'd like to have your view on the lazy + default approach.

**Comment by sven-schubert** [comment]
Sure. I will take a look at it.

**Comment by sven-schubert** [comment]
Hi,

is there a way to access the request / content body of the resulting request inside the "default => sub{...}"?
```
lib/Paws/Net/RestXmlCaller.pm:
if (my $xml_body = $self->_to_xml_body($call)){
      $request->content($xml_body);
}
```
That is what is required for calculating a valid MD5 hash.

**Comment by pplu** [comment]
I thought that there was no need to access the HTTP request from the `default => sub {}`. I thought that the Body/Content parameter was enough `MD5($self->Body)`. If it's not so... sorry for the mis-guided path.

**Comment by pplu** [comment]
Just pushed 0.35 with these changes. Thanks for your contribution!

**Comment by glenveegee** [comment]
Just a heads-up if you haven't already seen it the changes have broken PutObject see #210

**Pull request merged**
