### PR TITLE
Update some module dependencies

### PR DESCRIPTION
**Pull request by karenetheridge**
Hi, first of all thanks so much for this distribution!  We have recently switched to it in our AWS-heavy production environment and it is working great so far.  I noticed a few (very minor) issues though:

- the code uses File::Slurp, which has become quite problematic. I have changed this to File::Slurper -- if you only take one commit, please make it be this one.
- use of JSON.pm is switched to JSON::MaybeXS, to support more backends
- META.json included in the distribution
- a few author-specific tests are added, which I found helpful in debugging the earlier commits :)

If you have any questions, about any of these commits or Dist::Zilla in general, I'm quite happy to help. I noticed you're doing some interesting things with `lib/` generation at build time.. :)

### CODE REVIEW

**Comment by pplu** [comment]
Wow! Thanks for this great contribution!

**Comment by pplu** [comment]
Hi!

After merge I was getting some "Wide character errors" while generating APIs (reading the JSON definition files). I've changed read_text for read_binary, since that is what the JSON parser expects to see. Did you select read_text for any special cause?

**Comment by pplu** [comment]
Also, travis is failing the 00_compile tests. Do you imagine why?

https://travis-ci.org/pplu/aws-sdk-perl/builds/79356470

**Comment by karenetheridge** [comment]
> After merge I was getting some "Wide character errors" while generating APIs (reading the JSON definition files). I've changed read_text for read_binary, since that is what the JSON parser expects to see. Did you select read_text for any special cause?

Yes, generally one decodes/encodes utf8 *at the file boundary* (when reading/writing the file) -- and the JSON decoder expects to already see decoded (wide) unicode characters.  Passing around encoded strings in the application is not a good idea as you need to remember that particular strings are bytes and not characters, and need to be given special treatment.

If file read/writes are handling the utf8 encoding, then the JSON layer should not be -- there is a flag in the JSON library for this.

*however* -- using read_binary/write_binary is fine, as long as JSON content is the only thing these files are handling -- that is, you're not storing other content in these files as well, that would need separate encoding treatment.

**Comment by karenetheridge** [comment]
> Also, travis is failing the 00_compile tests. Do you imagine why?  
> https://travis-ci.org/pplu/aws-sdk-perl/builds/79356470

The errors indicate that the JSONAttribute trait is not being loaded -- those classes needs t `use Paws::API::JSONAttribute` (and `ParamInURI`, etc...) before using the trait.

**Pull request merged**
