### PR TITLE
S3 support: Issue 63

### PR DESCRIPTION
**Pull request by glenveegee**
Fix S3 API calls for methods that have requestURI syntax as follows {Key+}
Sign all S3 API Requests using Net::Amazon::Signature::V4
Include shapes with location: header in the request header

### CODE REVIEW

**Comment by pplu** [comment]
I've merged your changes into a branch named "s3support" (https://github.com/pplu/aws-sdk-perl/commits/s3support). Been working on getting S3 to return proper objects. I've created a TODO_in_branch file with items to get right on the branch.

**Comment by pplu** [comment]
Bit more news. PutObject wasn't working, but now is :smile:

Tell me what you want to work on so we don't duplicate efforts ;)

**Comment by glenveegee** [comment]
That's brilliant and thanks for the merge and return objects fix. In terms of functionality I'm looking to Put, Get, Copy and Delete. These actions would cover all our requirements and more (rename could be copy and delete). I'll look into the TODO_in_branch to make sure I'm not working on anything conflicting and let you know either way.

**Comment by pplu** [comment]
Great! If you can create a script that exercises a CreateBucket, GetObject, PutObject, Copy, ListObjects, DeleteBucket, etc, I can adapt that to the test suite, so that all functionality will be tested in the future.

**Comment by pplu** [comment]
Hiya!

  How are your tests going? Had any more problems with other methods? or is all seemingly going well?

**Comment by glenveegee** [comment]
Hi Jose,

Things are a bit hectic for me at the moment so things are a bit stalled.
I've written tests for a couple methods but I can already see the Create
bucket method is breaking and what the cause is. I'm not sure yet how to
fix it as it needs the CreateBucketConfiguration shape converted to content
in the payload and I'm afraid I'm not yet familiar enough with paws to get
this working.

I've nearly completed my other obligations so I can have a look at it again
fairly soon.

Sorry to keep you waiting on this.

Glen

**Comment by pplu** [comment]
Hi Glen

>Things are a bit hectic for me at the moment so things are a bit stalled.

No prob :) I'm just pinging to see status, and if I can help around ;)

>I've written tests for a couple methods but I can already see the Create
bucket method is breaking and what the cause is. I'm not sure yet how to
fix it as it needs the CreateBucketConfiguration shape converted to content
in the payload and I'm afraid I'm not yet familiar enough with paws to get
this working.

Wow! I've been looking at it, and it's what's keeping Route53 back too. It results that some APIs (S3 and Route53 at least) want you to send the parameters in the body in XML format (not in query parameters, nor in JSON in the body). I'll try to stub some code to guide you to completion :)

> I've nearly completed my other obligations so I can have a look at it again fairly soon.
> Sorry to keep you waiting on this.

Obligations go first. You have no obligation to report or to do something in a timely manner versus Paws. Don't feel sorry for "keeping me waiting": It's your time, and you can do what you want with it. I try to keep track, and help people get unstuck if that's the case. (BTW: push all the changes you want to your branch, as that let's me "inspect/merge" them and maybe work a bit on them too)

Thanks for the info!

**Comment by pplu** [comment]
Stubbing code for you, I thought I'd try a naive implementation for the XLM body. There's some code to generate the XML body "s3support" branch. It's quite ad-hoc and might need some cleaning up, but: 

I've been able to call CreateBucket succesfully :smile:
```
carton exec bin/paws S3 --region eu-west-1 CreateBucket Bucket paws-test-1 CreateBucketConfiguration { LocationConstraint eu-west-1 }
```

Hope it helps you continue with tests (note: your description of the problem helped me get right to the spot that needed changes)

**Pull request merged**
