### PR TITLE
Add minimum perl version using dzil plugin [MinimumPerlFast]

### PR DESCRIPTION
**Pull request by manwar**
Hi @pplu 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by pplu** [comment]
Hi!

Thanks for the PR! I have a doubt: how this plugin is determining the minimum perl version, or at least what version is being determined. Up till now Paws works on perl 5.10 forwards. Is that the minumum version that is being determined by this plugin?

**Comment by manwar** [comment]
Hi @pplu 

I would recommend the blog by Neil Bowers on this subject for more information.
http://blogs.perl.org/users/neilb/2014/08/specify-the-min-perl-version-for-your-distribution.html

Best Regards,
Mohammad S Anwar

**Comment by Grinnz** [comment]
This plugin automatically determines the minimum perl version based on modules and features used. If you want to manually specify it, you can instead add it to your cpanfile like:

requires 'perl' => '5.010001';

**Comment by pplu** [comment]
Hi,

   Looks like MinumumPerlFast was detecting 5.12 (https://travis-ci.org/pplu/aws-sdk-perl/builds/188359565).

   I've switched to specifying it in the cpanfile as @Grinnz suggested.

Thanks to the two of you

**Pull request merged**
