### PR TITLE
Hold back from latest Mixin::Linewise to support perl v5.10

### PR DESCRIPTION
**Pull request by aeruder**
Config::INI wants >= 0.105 but 0.109 requires perl 5.12.

### CODE REVIEW

**Comment by aeruder** [comment]
Hoping this is the only problem with v5.10 otherwise I'll have to recreate the build environment here.

**Comment by aeruder** [comment]
Sorry for the noise, that didn't work at all.

**Comment by Grinnz** [comment]
Specifying dependencies other than "minimum required" never really works well for CPAN distributions, since CPAN clients are not package managers.

**Comment by pplu** [comment]
@aeruder: Paws tries to not be too worried about very old Perl versions: https://github.com/pplu/aws-sdk-perl#perl-versions. 

Contributions have been accepted to get old versions working (like not using package { } syntax), but being compatible with very old versions of Perl is not a priority (putting the burden of supporting these old versions on the people and companies that use them, and not on the developers). I'd say that if a downstream package has broken 5.10 compatibility, we state that miniumum version is now 5.12, and leave 5.10 as a part of the pipeline that is allowed to fail, or delete it altogether.

**Pull request closed without merging**
