### PR TITLE
Fix failing unit tests for build on Ubuntu/Trusty64

### PR DESCRIPTION
**Pull request by glenveegee**
- Restructure JsonParamsService module so that unit tests run in ubuntu/Trusty64
   => Restructuring involved moving each package definition into it's own pm file
- Fix response YAMLs (add missing new line)

### CODE REVIEW

**Comment by pplu** [comment]
Hi!

Thanks for the contribution. I find it interesting, but don't understand why you've closed it ❓

**Comment by glenveegee** [comment]
I'm double checking that it works as I type. Will likely reopen it in the next 5 or so minutes

**Comment by pplu** [comment]
😆

**Comment by glenveegee** [comment]
Cool! Paws 0.30 deb file built successfully for ubuntu/trusty64. Do you think it would be possible to release this on CPAN?

**Comment by pplu** [comment]
Looks very good :)

Do you mind contributing how you build the deb package too? I'd like to add it to the documentation, so people can have different options

**Comment by glenveegee** [comment]
Hi. I use the cpan2deb tool to package Paws into a deb file. It's relatively straight forward but there are a number of dependencies that have to be built and packaged as well. Specifically, Furl Future::Mojo, Module::Build::Tiny, and Mojolicious

**Comment by Grinnz** [comment]
@glenveegee Furl, Future::Mojo and Mojolicious are all optional dependencies, but I don't know if that helps for packaging debs. On the other hand, Module::Build::Tiny should only ever be needed for the build process, so should be unnecessary as a packaged dependency. Do you know what module requires this?

**Pull request merged**
