### PR TITLE
Support AWS Instance Metadata Service V2 (IMDSv2)

### PR DESCRIPTION
**Pull request by 0leksii**
Implement support of new version of AWS Instance Metadata Service.
Update calls to be the same as described at the following document:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#instance-metadata-v2-how-it-works

### CODE REVIEW

**Comment by nunofernandes** [comment]
Hello,

Can this be merged and released?

Thanks

**Comment by 0leksii** [comment]
> Hello,
> 
> Can this be merged and released?
> 
> Thanks

@pplu can you approve this?

**Comment by byterock** [comment]
It think I have permission to pull it I think PPLU has to approve the final release

**Comment by pplu** [comment]
Paws 0.45 just hit CPAN with your Merge Request applied

Thank you

**Comment by nunofernandes** [comment]
Hi... 

I'm still seeing 0.44 in cpan

image

Anything missing to have that updated?

Thanks

**Comment by pplu** [comment]
@nunofernandes : I'm also seeing 0.44. I resubmitted 0.45 for reindexing some days ago, but no luck: I'm seeing 0.44 still. I get a message confirming that it is queued for indexing, but I don't get a success (or failure message) from PAUSE

I think @castaway has some contact with PAUSE maintainers, and can maybe help us know if there is some problem with the upload. Can @castaway either help, or tag someone that can help out know why Paws isn't being published to CPAN?

**Comment by nunofernandes** [comment]
@castaway , can you help on this issue please? :prayer_beads:

**Pull request merged**
