### PR TITLE
Generate method Synopsis from example json, or from known shapes - NEEDS REVIEW

### PR DESCRIPTION
**Pull request by castaway**
This needs reviewing / testing! Our AWS account is stuck, so I haven't yet been able to directly test these. (Waiting on Amazon to fix it..)

Please have a look over the generated Synopsis and let me know if these look/seem correct

### CODE REVIEW

**Comment by pplu** [comment]
Wow! I just have one word for this PR: It looks awesome!

Things I've found after seeing the generated docu are:

An enum is outputted like this:
```
      CertificateStatuses => [
        'MyCertificateStatus',
        ... # values: PENDING_VALIDATION, ISSUED, INACTIVE, EXPIRED, VALIDATION_TIMED_OUT, REVOKED, FAILED
      ],    # OPTIONAL
```
the `MyCertificateStatus` text confuses me a bit (since the strings seen before have this same form. Maybe it can be changed for `CertificateStatusValue` or `CertificateStatusEnum`, or one of the enum values. What do you think?

It looks like some long comments in the SYNOPSIS don't get padded (I think they will not have the correct "code" formatting. An example is:
```
=head1 SYNOPSIS

    my $autoscaling = Paws->service('ApplicationAutoScaling');
# To delete a scaling policy
# This example deletes a scaling policy for the Amazon ECS service called web-app, which is running in the default cluster.

    my $DeleteScalingPolicyResponse = $autoscaling->DeleteScalingPolicy(
```

Methods that don't return have the 
```
  # Results:
```
but nothing follows them. An example is `ApplicationAutoScaling`s `DeleteScalingPolicy`.

When a method returns, the data is accessed as methods.
```
  # Results:
  print $DescribeScalingActivitiesResponse->{ScalingActivities};
```
will work, but that's accessing the internals of the Moose object. It should be a method call
```
  # Results:
  print $DescribeScalingActivitiesResponse->ScalingActivities;
```

When the example returns an array:
```
    my $AutoScalingGroupsType = $autoscaling->DescribeAutoScalingGroups(
      {
        'AutoScalingGroupNames' => ['my-auto-scaling-group']
      }
    }
    );

  # Results:
  print $AutoScalingGroupsType->{AutoScalingGroups};
  #
    [

      {
        'MaxSize' => 1,
        'AutoScalingGroupARN' =>
```
It looks like the AutoScalingGroups returns an array of HashRefs. Paws returns an Array of objects.

```
    my $DescribeAutoScalingNotificationTypesAnswer =
      $autoscaling->DescribeAutoScalingNotificationTypes(
    }
      );
```
There is a runaway curly in the method call

I've started branch feature/json_examples_227 on my repo too. I've pushed a commit that silences the warnings from the sprintfs.

Generation times have gone up significantly. I've traced this to PerlTidy. The multiple calls to Perl::Tidy::perltidy are the cause. Can it be that inititializing PerlTidy in every call takes a lot of time? (I haven't verified this). Maybe there's a way of initializing a PerlTidy tidier object that can later tidy Perl code? (I've looked around in the PerlTidy docu a bit, but haven't found anything evident). I'm not super worried about generation times (better slow and correct than fast 😄 )

Keep up the brilliant work 💯

**Comment by castaway** [comment]
Updated to fix most of these,, Still need to fix the "result is actually an object" one (shame, dumping hashrefs is easy ;)

Wondering if I print it as the dump of an object, or just do some examples of calling methods on it, and link to the result object doc... any thoughts?

**Comment by pplu** [comment]
> Wondering if I print it as the dump of an object, or just do some examples of calling methods on it, and link to the result object doc... any thoughts?

I think that an example of method calls is better (I've seen newbies accessing objects internals as hashrefs because they're following Data::Dumpers outputs, and it worked).

**Comment by castaway** [comment]
I've split the difference for now, and changed them to simple method call examples, with a link to the doc for the output object.

See latest update.

I have also pulled in current release/0.37

**Comment by castaway** [comment]
Hi @pplu , have another look please?

Tho I've just discovered (sigh), that I didn't take account of the "location" info, thus my example for PutBucketCors contains:

`      ContentMD5 => 'MyContentMD5',                          # OPTIONAL`

which according to service-1.json is a header:
`        "ContentMD5":{
          "shape":"ContentMD5",
          "location":"header",
          "locationName":"Content-MD5"
        },`

and thus I assume should not be displayed?

**Comment by pplu** [comment]
I haven't found anything that I consider important to add, so if you feel confident for merging, I will merge after your confirmation.

A couple of non-important things that could be improved (this would not block the merge):
 - For enums with lots of values, in the code example, the comment with all the values can get quite long. Maybe we can consider shortening the list aaa, bbb, ... zzz
 - Also, maybe we can quote the enum values so that copy & paste is easier

Let me tell you that this PR is really great. I appreciate all the work that you have put into it. It pushes the documentation to a new level :1st_place_medal:

**Comment by castaway** [comment]
Let's merge it before it diverges too far from other changes to Builder.pm, I'm happy for that to happen. We can add the minor issues as github issues, so they can be picked up later.

thanks!

**Comment by pplu** [comment]
> Tho I've just discovered (sigh), that I didn't take account of the "location" info, thus my example for PutBucketCors contains:

>ContentMD5 => 'MyContentMD5', # OPTIONAL

>which according to service-1.json is a header:
"ContentMD5":{ "shape":"ContentMD5", "location":"header", "locationName":"Content-MD5" },

>and thus I assume should not be displayed? .. or displayed in another way? it looks like botocore hide the ContentMD5 headers from users - https://github.com/boto/botocore/blob/develop/botocore/handlers.py#L998-L1005

Don't worry: Paws doesn't hide the Content-MD5 parameter. If you don't specify it, it will get auto-calculated, so the initial `ContentMD5 => 'MyContentMD5', # OPTIONAL` is fine

**Pull request merged**
