### PR TITLE
massive json decode speed improvement

### PR DESCRIPTION
**Pull request by aeruder**
As noted in the commits, this is some small changes extracted from @castaway's work on the shadowcat mooification branch.  This provides a very large portion of the speedups on that branch without any of the more extensive work converting things to Moo.  I've left Jess as the author on the commit as this was definitely not my work but I think it would be very valuable as part of Paws.

Also, this adds a few benchmark/profiling scripts that can be used to identify some of these hotspots and determine worthy optimizations.

### CODE REVIEW

**Comment by pplu** [comment]
Very nice work indeed!

You seem to be getting familiar with the codebase, and the different branches (others would have repeated @castaway work!).

I am trying to not be a bottleneck in Paws development and release (@byterock finished and uploaded 0.43!) so if you deem you would like to participate, I can give you broader permissions.

**Comment by castaway** [comment]
thanks!

**Comment by byterock** [comment]
Hmm do we want to put this in now as release .44?  keep the changes smaller but the release more frequent?

**Comment by pplu** [comment]
> Hmm do we want to put this in now as release .44? 
I would :) 

> keep the changes smaller but the release more frequent?
I know that there was a release plan to get all the shadowcat work in, but if there is a new release before doing that, it won't affect anything. After all, good help is a scarce thing, so lets take it and ship it to the community :)

I merged a couple of the code-generation contributions, but didn't merge this because I was trying to get a hold of whats in Paws 0.43 because of this: https://metacpan.org/release/BYTEROCK/Paws-0.43/diff/JLMARTIN%2FPaws-0.42/lib/Paws.pm. I'm not sure if 0.43 has the same stuff as 0.42 (although the Changes file seems to be from 0.43)...

**Comment by aeruder** [comment]
I think its worthwhile waiting for #411 for sure for a 0.44.  Without it dynamodb (and perhaps others) is near unusable.

**Comment by pplu** [comment]
@aeruder : I agree. I think those DynamoDB changes are good for a release on their own...

**Comment by pplu** [comment]
Just pushed 0.44 to CPAN with this PR. Thank you for your contribution!

**Pull request merged**
