### PR TITLE
WIP: Fix/issue 212

### PR DESCRIPTION
**Pull request by pplu**
This is a work in progress to fix issues reported in #212

### CODE REVIEW

**Comment by byterock** [comment]
What do I need to do to get this in the next version .40 of PAWS??

I am willing to do the work I just need to know what I have to do??

**Comment by pplu** [comment]
Was the code on this branch working for you OK in 0.39? Since the last message on Issue 212 said that there were still some bugs to fix, I thought this PR was still incomplete.

To get this into 0.41 (0.40 is already on CPAN), basically I need confirmation on your part that the changes are working, since the code conflicts are trivial to fix.

**Comment by byterock** [comment]
Ok back on  some time to work on this.  I have been playing with the master branch and it seems to work fine for the few tests I have for pinpoint

I do have a follow on question.  Where to the changes for botocore go??  just in the https://github.com/pplu/botocore  branch??

**Comment by pplu** [comment]
> I do have a follow on question. Where to the changes for botocore go?? just in the https://github.com/pplu/botocore branch??

They go in the "develop" branch of "my fork" of botocore. Please open a branch from there if you're going to propose changes. I'd try to keep them to a minimum (since most of problems are solvable from the builders).

**Comment by byterock** [comment]
Ok looks like I need some botocore changes added in.  Just having a little problem getting all the little parts to work lets take 'Pinpoint/PhoneNumberValidate' for an example

I think what you want me to change the Pinpoint/PhoneNumberValidate.pm file  rather than the botocode the 'service-2.json'  file for pinpoint?

so this
```

package Paws::Pinpoint::PhoneNumberValidate;
  use Moose;
--  has NumberValidateRequest => (is => 'ro', isa => 'Paws::Pinpoint::NumberValidateRequest', required => 1);
++  has NumberValidateRequest => (is => 'ro', isa => 'Paws::Pinpoint::PhoneNumberValidateRequest', required => 1);

  use MooseX::ClassAttribute;
--class_has _stream_param => (is => 'ro', default => 'NumberValidateRequest');
++class_has _stream_param => (is => 'ro', default => 'PhoneNumberValidateRequest');


```
rather than this in Botocore
```

 "PhoneNumberValidate" : {
      "name" : "PhoneNumberValidate",
      "http" : {
        "method" : "POST",
        "requestUri" : "/v1/phone/number/validate",
        "responseCode" : 200
      },
      "input" : {
        "shape" : "PhoneNumberValidateRequest"
      },
      "output" : {
--      "shape" : "NumberValidateResponse",
++        "shape" : "PhoneNumberValidateResponse",
        "documentation" : "200 response"
      },

```

Cheers John

**Comment by pplu** [comment]
@byterock : that looks like a thing to patch in botocore :+1:

**Comment by byterock** [comment]
Ok changes to botocore as well 
I will be working on this branch 

https://github.com/byterock/botocore/tree/devlop-212

of botocore

**Comment by byterock** [comment]
Ok I ran a test suite on  all the calls I got them all to work 

checked in all my code changes for botocore here

https://github.com/byterock/botocore/tree/devlop-212

and the present   branch here has my changes for lib/Paws

Any Idea when the version with these changes will get out to CPAN

**Comment by byterock** [comment]
Is this  goint to get into 41?  and if there is anything I can do to help with 41 let me know.  I will see if I can find some time to work on other bugs/features

**Comment by pplu** [comment]
Hi, Yes, this will get into 0.41. I don't know the date yet (should be along next week).

**Pull request closed without merging**
