### PR TITLE
(Travis) CI is dead, long live the (GitHub) CI!

### PR DESCRIPTION
**Pull request by JRaspassOleeo**
- Bump the latest Perl in the GH Actions
 - Bump the checkout action
 - Reduce the verbosity of CI tests
 - Drop the obsolete .travis.yml file
 - Switch the README CI status icon to GitHub
 - Update some mentions of Travis
 - Replace ok(1)/ok(0) with pass/fail in tests
 - Replace $ENV{TRAVIS} with $ENV{CI} in tests
 - Consistently use $ENV{AUTHOR_TESTING} in tests

### CODE REVIEW

**Comment by byterock** [comment]
I am fine with this change.  Will have to get back to PAWS after a bit of an absence.  Do any of the other maintainers have any comments.  I do not use CI myself

**Review by castaway — APPROVED** [review]
looksgood to me

**Comment by JRaspassOleeo** [comment]
Thanks for the quick replies! Glad to see this project isn't dead, which is good because this PR was meant to be an initial "test the waters" PR before I try upstreaming fixes we've made locally when trying to use this library in anger at $work.

**Comment by castaway** [comment]
You're welcome. I don't use it / work for anyone that does at the mo (my previous maint was sponsored).. Happy to review etc tho!

**Comment by byterock** [comment]
seems to be no problem so far so I am going to push the button

**Pull request merged**
