### PR TITLE
Fixed Route53 ListResourceRecordSets API uri

### PR DESCRIPTION
**Pull request by coreymaher**
It looks like the Route 53 ListResourceRecordSets URI is incorrect. This pull request should fix it.

### CODE REVIEW

**Comment by coreymaher** [comment]
Hmm I see now that this file is automatically generated so this is probably not the right place to make this change. I'm not quite sure I understand where this URI came from though, or where upstream I need to fix it.

**Comment by pplu** [comment]
Hi!

Thanks for the PR! You're right, the file is autogenerated, but it helps me even if you correct auto-generated files, because then I can track down what's happening.

The URI is coming from https://github.com/pplu/botocore/blob/develop/botocore/data/route53/2013-04-01/service-2.json (a fork that I maintain of botocore, the python SDK for AWS, with some customizations for the Perl SDK).

It looks like the URI in the call isn't correct, just as you pointed out. Have you tried out more Route53 operations? Is Route53 working correctly for you?

**Comment by coreymaher** [comment]
Ah okay. I created a pull request on boto/botocore https://github.com/boto/botocore/pull/548
Would you like me to create one for your fork as well?

I haven't tried out many of the Route53 calls, just ListHostedZones and ListResourceRecordSets.

**Comment by pplu** [comment]
OK, I see what's happening (based on the PR that you did to botocore, and why they won't merge it). We don't support the Location for URIs (yet) (the R53 API is still unstable / unfinished). Are you interested in building support for that?

**Comment by coreymaher** [comment]
Unfortunately I don't have much experience with this module, or the aws APIs in general. I could take a look, but I'm not really sure where to start.

**Comment by pplu** [comment]
Of course I'll help you get around the code and how to fix it :) If you want, wait for my next message on this thread for instructions.

**Comment by pplu** [comment]
I'll tell you the plan: It results that the "location for URI parameters" is implemented in RestJSON services, but not in RestXML (which Route53 is).
So what we want to do is:

1 - Replicate the behaviour that the RestJSON services have in the builder.
You'll find in builder-lib/Paws/API/Builder/restjson.pm
```
[%- IF (shape.members.$param_name.location == 'uri') %], traits => ['ParamInURI'], uri_name => '[% shape.members.$param_name.locationName %]' [% END %]
```
we want that in the restxml.pm builder. Regenerate the auto-lib classes with ./gen_classes.pl. A whole bunch of classes should now have a new trait for signalling when that parameter should be in the header, and what value it should have.

2 - Now that we have the information for what params go in headers, and what goes in the body: we need to do what "sub _call_uri" in lib/Paws/Net/RestJsonCaller.pm does, but in lib/Paws/Net/RestXmlCaller.pm

And you should be done!

**Comment by pplu** [comment]
Any luck? Want more help?

**Comment by coreymaher** [comment]
Unfortunately I haven't had time to look yet. I probably won't be able to until the weekend

**Comment by pplu** [comment]
Hey! Finally I got to it in b70bd673be9d4e1e07930cb74e5a31b9a3cca05f. The version on CPAN (0.12) has the call working.

Cheers, and don't doubt reporting more bugs :)

**Pull request closed without merging**
