### PR TITLE
Add links to AWS docs

### LINKED ISSUE #84: Add links to AWS docs
It would be super helpful if all of the docs linked to the related docs that amazon publishes.  Like for example, if https://metacpan.org/pod/Paws::CloudWatch#DeleteAlarms-AlarmNames-ArrayRef-Str (and https://metacpan.org/pod/Paws::CloudWatch::DeleteAlarms) linked to http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DeleteAlarms.html

### PR DESCRIPTION
**Pull request by piratefinn**
Fixes #84 
Adds in a URL to the doc of a class. It checks for an existing URL via the servicePrefix and adds that at the end of the aws top level doc URL and if that does not respond correctly, instead simply adds the top level aws documentation page.
Part of the sponsored team for ZipRecruiter along with castaway.

### CODE REVIEW

**Comment by pplu** [comment]
Hi!

When I tried out generating, it seemed strange that all the links were actually pointing to a service (no generic documentation urls are being generated).

For example, https://aws.amazon.com/documentation/api.pricing/ and https://aws.amazon.com/documentation/email/ are invalid URLs, so it looks like something about the link detection is not working for me.

Also, to make the links clickable in POD you need to surround them in L<URL> (you're missing the L)

It would be helpful that you warn about when you're assigning a default documentation URL to a service (so at least when they get used, it appears in the `make gen-classes` output)

Can you take a look at these issues?

**Comment by piratefinn** [comment]
Sorry about that, fixed both issues. Should make gen-classes be run before this request is pulled?

**Comment by pplu** [comment]
Hi,

  Your changes are looking good :smile:. I've pulled them onto my repo on branch feature/issue-84, and added some code to let us manually specify documentation URLs for services (I've added a liveness check for them too). Do you think you can find a docu link for the rest of missing services?

BTW: it's best you not include all the generated classes in the PR (since it helps me see the differences that your code adds).

**Comment by piratefinn** [comment]
Gotcha, will note on the last point.
I had done the investigation of doc links for the missing services and will show the missing services listed below. The main issue I ran into regarding that is the only way I could see a workaround was editing botocore itself...except the service-2.json as you know is auto generated.

`ACMPCA.pm, Budgets.pm, CloudDirectory.pm, CloudHSMv2.pm, CloudSearchDomain.pm, CloudWatchEvents.pm, CloudWatchLogs.pm, CloudWatch.pm, CognitoIdentity.pm, CognitoIdp.pm, CognitoSync.pm, CostExplorer.pm, CUR.pm, DAX.pm, Discovery.pm, DS.pm, DynamoDBStreams.pm, EFS.pm, ES.pm, FMS.pm, IoTData.pm, IoTJobsData.pm, KinesisAnalytics.pm, KinesisVideoArchivedMedia.pm, KinesisVideoMedia.pm, KinesisVideo.pm, LexModels.pm, LexRuntime.pm, MachineLearning.pm, MarketplaceCommerceAnalytics.pm, MarketplaceEntitlement.pm, MarketplaceMetering.pm, MediaStoreData.pm, MigrationHub.pm, MobileHub.pm, MQ.pm, MTurk.pm, OpsWorksCM.pm, Pricing.pm, ResourceGroups.pm, ResourceTagging.pm, Route53Domains.pm, SageMakerRuntime.pm, SDB.pm, ServiceDiscovery.pm, SES.pm, SMS.pm, SSM.pm, StepFunctions.pm, STS.pm, Support.pm, WAFRegional.pm`

**Comment by pplu** [comment]
I wouldn't try to touch the service-2.json files in botocore (as they are controlled by AWS, and it can be slow to get something into them).

If you like, we can create a json file with the overrides (or all the links, for that purpose), and point the aws team to it, so they can decide how and where to put the information (if they want it).

**Comment by piratefinn** [comment]
This can be indeed done and I should be able to throw together a list of the terms used that would essentially be checked for existing before making the "guess" URL that this current PR does.

Honestly though for the further development of this project and AWS linking, I'd refer to what is described in #85 by spazm, who describes the somewhat undocumented voodoo magic /goto/ links that exists which work _if_ the API documentation is inside a certain ApiReference URL formatting, which a number of them are. This is also what the botocore docs currently uses for their API class links, however they do a blanket assumption that the link works, where if it doesn't, it redirects to the main /documentation/ top level page.
If the AWS team gave more information on how this magic redirect works that would be lovely and make this entire job a lot easier, since then automated URL constructions would be far simpler. Plus for lovely class level documentation.

**Comment by piratefinn** [comment]
So parts of the service link code and have added "goto" linking to operations, with the ability to overwrite somewhat, which people can submit their own of for those that don't work, opworks-cm has been added as an example one where it is relevant.

One main issue with the overwrite is it will not work for URL's which do not use the CamelCase names, such as:

- https://docs.aws.amazon.com/greengrass/latest/apireference/disassociaterolefromgroup-delete.html
- https://docs.aws.amazon.com/apigateway/api-reference/resource/api-keys/
- https://docs.aws.amazon.com/amazonglacier/latest/dev/api-multipart-abort-upload.html

Ideally, these overrides are stored in a JSON, which thus could have stored with it some extra options on how to parse it. For now however there is a structure in place to override, along with goto linking itself. goto redirects are tested for if they redirect to https://aws.amazon.com/documentation/, so that if they do, they are undefined and thus not inserted.

**Comment by pplu** [comment]
Hi,
   I'd like you to take a look at my last commits on https://github.com/pplu/aws-sdk-perl/tree/feature/issue-84.
   I've added more docu URLs to the override hash, corrected some TT, and made the class generation faster by doing all the HTTP heads in parallel. Can you look to see that this works as expected for you?

**Comment by piratefinn** [comment]
It _works_, however I get bickered at with errors. See [here](https://gist.github.com/piratefinn/48c82dadd75cd8316609a06259da4fe8)

**Comment by pplu** [comment]
I've opened a ticket to https://github.com/Corion/future-http/issues/2 silence the warnings. Note: the output is a bit easier on the eyes if you're not using Carp::Always 😆

**Comment by piratefinn** [comment]
Yeah, I was trying to figure out what was giving the warnings, but it looks like you had the same. At least it is a warning but still functional then. Otherwise though it worked for me.

**Comment by piratefinn** [comment]
On mst's recommendation I switched to a different Future method. I've also improved on the parallelisation by using fmap_scalar so we can decide on the level of concurrency, along with a check for if it redirects to the base doc URL with a warn much like you added to service_url. I switched UA to Mojo::UserAgent so I had access to Mojo::Promise for this and switched it where relevant so LWP was no longer needed.

**Comment by shadowcat-mst** [comment]
Future::HTTP is bizarre and was originally AnyEvent only until I pointed out the interop issues - unless you have very specific requirements, using the built in future/promise returning stuff in IO::Async or Mojo (depending on which of those two you're using) is much simpler.

**Comment by pplu** [comment]
I've pushed a commit that splits the process into two parts:
one generates a documentation-1.json files for each service, and the class generation just consumes them. This has three motives:
 - recover class generation speed
 - not depend on online connectivity for generating classes
 - make the generation repeatable

What do you think? Can you review if this code still generates the documentation that you were generating?

**Comment by piratefinn** [comment]
This appears to work for me after running gen_docu_links.pl then doing the make. One issue I ran into is during generation of the documentation-1.json files is "medialive" failed for me, because the service-2.json for it has occurrences of duplicate keys, more specifically in "shapes" it errored on there being multiple "CreateInputResponse" (line 2078 & 2150), noting that Cpanel::JSON::XS is the one which will error from duplicate keys. This issue is stopping the auto-lib docs for medialive from being generated entirely.

**Comment by pplu** [comment]
Just merged this for the next release

**Pull request merged**
