### PR TITLE
Changed Paws::SQS::AttributeMap attributes for #25

### PR DESCRIPTION
**Pull request by codehead**
Message side of the deal to complement commit ae34084 to fix issue #25

### CODE REVIEW

**Comment by pplu** [comment]
Got that fixed in master. I added the wrong properties the first way around :_(
I'll wait a bit to have feedback from you before considering this fix as done

**Comment by codehead** [comment]
Cool! Except that *both* ApproximateFirstReceiveTimestamp and SentTimestamp appear twice.
Getting there!

**Comment by codehead** [comment]
I *know* it's not your fault. The JS-AWS docs in Dash have the wrong attribute names in the receiveMessage example, and it looks like it is wrong in aws-sdk-core-ruby/apis/source/sqs-2012-11-05.json as well, so after I stopped banging my head and identified the problem I naturally assumed the bug permeated from upstream while auto-generating the Perl version.

**Comment by pplu** [comment]
All yours in master :)

**Comment by pplu** [comment]
How is SQS working now? Can you confirm that the code is OK?

**Comment by codehead** [comment]
All A-OK! Thx!

**Pull request closed without merging**
